spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update
        properties.hibernate.jdbc.time_zone: UTC
    datasource:
        url: jdbc:postgresql://localhost:5432/proseo
        username: <db_user>
        password: <db_pwd>
logging:
    file: /proseo/log/proseo-model.log