- name: Install rkhunter
  yum:
    name: rkhunter
    state: latest

- name: Set rkhunter notification email
  lineinfile:
    path: /etc/sysconfig/rkhunter
    regexp: "^ *MAILTO.*"
    line: "MAILTO={{ alert_email|default('root@localhost') }}"
    create: yes
    state: present

- name: Disable rkhunter SSH root users
  lineinfile:
    path: /etc/rkhunter.conf
    regexp: "^ALLOW_SSH_ROOT_USER=.*"
    line: "ALLOW_SSH_ROOT_USER=no"
    create: yes
    state: present

- name: Disable rkhunter SSH protocol
  lineinfile:
    path: /etc/rkhunter.conf
    regexp: "^ALLOW_SSH_PROT_V1=.*"
    line: "ALLOW_SSH_PROT_V1=0"
    create: yes
    state: present
