logging:
    file: /proseo/log/proseo-xbip-monitor.log
    level:
        root: INFO
        de.dlr.proseo: TRACE
 #       org.apache.http: DEBUG
 #       org.springframework.web.client: DEBUG
proseo:
    xbip:
        # XBIP Monitor identifier (must be unique for all XBIP monitors on the same host)
        id: PTS-INU
        # Satellite identifier (e. g. "PTS", "S5P" ...)
        satellite: PTS
        # Path to the XBIP directory (mounted WebDAV volume)
        directory: /Path/to/WebDAV/volume/NOMINAL
        # Interval between pickup point checks in milliseconds (e. g. every min)
        check.interval: 60000
        
        # Download history
        history:
            # Path to the file for storing transfer history (on a persistent volume)
            file: /Path/to/transfer/history/file
            # Interval to truncate transfer history file in milliseconds (e. g. daily)
            truncate.interval: 86400000
            # Period to retain transfer history entries for, in milliseconds (e. g. one week)
            retention: 604800000
            
        # Minimum size in bytes of a file to be used for performance measurements (e. g. 20 MiB = 20 * 1024 * 1024 Bytes)
        performance.minsize: 20971520
        
        ## Multi-threading control
        #session:
            ## Maximum number of parallel transfer sessions (default 1 = no parallel downloads)
            #maxthreads: 1
            ## Interval in millliseconds to check for completed transfer sessions (default 500 ms)
            #wait: 500
            ## Maximum number of wait cycles for transfer session completion checks (default 3600 = total timeout of 30 min)
            #maxcycles: 3600
        #file:
            ## Maximum number of parallel file download threads within a download session (default 1 = no parallel downloads)
            #maxthreads: 1
            ## Interval in millliseconds to check for completed file downloads (default 500 ms)
            #wait: 500
            ## Maximum number of wait cycles for file download completion checks (default 3600 = total timeout of 30 min)
            #maxcycles: 3600
            
    l0:
        # path to the target CADU directory (for L0 processing)
        directory.cadu: /Path/to/CADU/directory
        # command to execute for L0 processing
        command: /Path/to/L0/processing/script 
