version: '3'
services:
  proseo-db:
    image: ${REGISTRY_URL}/postgres:11.5-integration-rc1-${PROSEO_REVISION}
    environment:
      - POSTGRES_DB=proseo
      - POSTGRES_PASSWORD=sequel09Master
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  proseo-ingestor:
    image: ${REGISTRY_URL}/proseo-ingestor:0.1.0-SNAPSHOT-integration-rc1-${PROSEO_REVISION}
    ports:
      - "8081:8080"
    depends_on:
      - proseo-db
  proseo-order-mgr:
    image: ${REGISTRY_URL}/proseo-order-mgr:0.1.0-SNAPSHOT-integration-rc1-${PROSEO_REVISION}
    ports:
      - "8082:8080"
    depends_on:
      - proseo-db
  proseo-prodplanner:
    image: ${REGISTRY_URL}/proseo-planner:0.1.0-SNAPSHOT-integration-rc1-${PROSEO_REVISION}
    ports:
      - "8083:8080"
    depends_on:
      - proseo-db
  proseo-processor-mgr:
    image: ${REGISTRY_URL}/proseo-processor-mgr:0.1.0-SNAPSHOT-integration-rc1-${PROSEO_REVISION}
    ports:
      - "8084:8080"
    depends_on:
      - proseo-db
  proseo-productclass-mgr:
    image: ${REGISTRY_URL}/proseo-productclass-mgr:0.1.0-SNAPSHOT-integration-rc1-${PROSEO_REVISION}
    ports:
      - "8085:8080"
    depends_on:
      - proseo-db
  proseo-gui:
    image: ${REGISTRY_URL}/proseo-ui-gui:0.1.0-SNAPSHOT-integration-rc1-${PROSEO_REVISION}
    ports:
      - "8087:8080"
    depends_on:
      - proseo-ingestor
      - proseo-prodplanner
      - proseo-order-mgr
      - proseo-processor-mgr
      - proseo-productclass-mgr
  proseo-pgadmin:
    image: ${REGISTRY_URL}/dpage/pgadmin4:2019-11-12-2-integration-rc1-${PROSEO_REVISION}
    environment:
      - PGADMIN_ENABLE_TLS=True
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - "/etc/ssl/certs/proseo-selfsigned.crt:/certs/server.cert"
      - "/etc/ssl/certs/proseo-selfsigned.key:/certs/server.key"
    ports:
      - "8443:443"
    depends_on:
      - proseo-db
volumes:
  pgdata:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24
